<?php

    require_once'class_inclusion.php';
    require_once'class_dispensation.php';
    require_once'class_etat_dispensation.php';
    require_once'class_ligne.php';
    require_once'class_patient.php';
    require_once'class_profil_serologique.php';
    require_once'class_protocole.php';
    require_once'class_type_protocole.php';
    require_once'class_suivi_patient.php';
    require_once'class_grade.php';
    require_once'class_utilisateur.php';
    require_once'class_ass_grade_droit.php';
    require_once'class_droit.php';
    require_once'class_medicament.php';
    require_once'class_repartition_adulte.php';
    require_once'class_repartition_enfant.php';
    require_once'class_inclusion.php';
    require_once'class_rapport.php';
    require_once'class_co_infection.php';
    require_once'class_rdvJour.php';
    require_once'class_repartitionPoids.php';
    require_once'class_graphe.php';